### ISSUE TITLE
为什么会形成竞态条件！

### ISSUE THREAD

**Issue by liuweiccy** [gopcp/example.v2#10]
[cow.go](https://github.com/gopcp/example.v2/blob/master/src/gopcp.v2/chapter5/value/cow/cow.go) 41- 44 行
`func (array *intArray) Set(index uint32, elem int) (err error) {
	if err = array.checkIndex(index); err != nil {
		return
	}
	if err = array.checkValue(); err != nil {
		return
	}

	// 不要这样做！否则会形成竞态条件！
	// oldArray := array.val.Load().([]int)
	// oldArray[index] = elem
	// array.val.Store(oldArray)

	newArray := make([]int, array.length)
	copy(newArray, array.val.Load().([]int))
	newArray[index] = elem
	array.val.Store(newArray)
	return
}`

**Comment by hyper0x** [comment]
先原子的加载，再原子的存储，这属于两步。如果在这两步之间其他goroutine改了oldArray，那么还是会因并发地修改oldArray产生竞态套件，以至于这两个原子操作对oldArray的保护失效。
