### ISSUE TITLE
存在并发的风险，可能在get的过程中有Delete和Put操作

### ISSUE THREAD

**Issue by cyongxue** [gopcp/example.v2#23]
func (s *segment) GetWithHash(key string, keyHash uint64) Pair {
	s.lock.Lock()
	b := s.buckets[int(keyHash%uint64(s.bucketsLen))]
	s.lock.Unlock()
	return b.Get(key)					// 存在并发的风险，可能在get的过程中有Delete和Put操作
}

**Comment by hyper0x** [comment]
你可以看看bucket.go和pair.go中的代码，它们都用到了原子操作。
