### ISSUE TITLE
注册器的Get方法多写了几行无用代码

### ISSUE THREAD

**Issue by wenCcc** [gopcp/example.v2#24]
https://github.com/gopcp/example.v2/blob/01be33ae0e6a5a1e4647a3dfaa53a0f6843451aa/src/gopcp.v2/chapter6/webcrawler/module/registrar.go#L99

这三行应该是多余的吧

**Comment by hyper0x** [comment]
收到。经过核实，这三行确实是没必要的代码，稍后我会fix掉。谢谢！
