### ISSUE TITLE
5.3.6 ConcurrentArray的Set方法实现疑问

### ISSUE THREAD

**Issue by darkbloodx** [gopcp/example.v2#5]
`chapter5/value/cow/cow.go`中`Set`方法：
```
	newArray := make([]int, array.length)
	copy(newArray, array.val.Load().([]int))
	newArray[index] = elem
	array.val.Store(newArray)
```
这样实现是否会有并发问题？复制和设值这段是否需要加锁？

**Comment by toenola** [comment]
这段并发写入时会有问题,  反而错误示例的那部分代码可以保证并发写入结果是正确的
`// 不要这样做！否则会形成竞态条件！
	 oldArray := array.val.Load().([]int)
	 oldArray[index] = elem
	 array.val.Store(oldArray)`

**Comment by lsytj0413** [comment]
一个简单的测试:
`
	arr := sync.NewConcurrentArray(10)
	l := 10
	var wg ssync.WaitGroup
	wg.Add(l)
	for i := 0; i < l; i++ {
		go func(i int) {
			defer wg.Done()

			for j := 0; j < 1000; j++ {
				err := arr.Set(uint32(i), j)
				if err != nil {
					fmt.Println(err)
				}
			}
		}(i)
	}

	wg.Wait()

	for i := 0; i < l; i++ {
		fmt.Println(arr.Get(uint32(i)))
	}
`

在我本地的输出为:

`
999 <nil>
998 <nil>
944 <nil>
999 <nil>
974 <nil>
914 <nil>
847 <nil>
954 <nil>
922 <nil>
999 <nil>
`

**Comment by hyper0x** [comment]
这里不用加锁。原因是，我是原子地取出val中的值的，然后我一个接一个地取出该值总的元素值，当修改完了之后，我再原子地存入一个*新*的值，旧的值永远不会被并发地修改。所以这里不需要加锁。
