### ISSUE TITLE
apipe example 运行出错

### ISSUE THREAD

**Issue by zh1014** [gopcp/example.v2#9]
Run command `echo -n "My first command comes from golang."`: 
My first command comes from golang.

Run command `ps aux | grep apipe`: 
Error: Couldn't wait for the second command: exit status 1

**Comment by hyper0x** [comment]
你用的什么版本？我本就环境没有问题。

```
Run command `echo -n "My first command comes from golang."`: 
My first command comes from golang.

Run command `ps aux | grep apipe`: 
haolin            8978   0.0  0.0 558433396   1472 s002  S+    7:35下午   0:00.01 apipe
```

**Comment by Alex-liutao** [comment]
你是把代码拷贝到自己的项目中运行的，还是直接运行的示例呢？
我觉得这个问题的原因是，`ps` 找不到名为 `apipe` 的进程。所以如果你这段代码运行的进程名称不叫`apipe`的话，就会报这个错。

如果你是把代码粘贴到你自己的项目中运行的话，尝试把`cmd2 := exec.Command("grep", "apipe")` 里面的"apipe"改成的你的项目编译出来的程序的名字

**Comment by hyper0x** [comment]
我觉得这个问题不用纠结吧，你用`go run`命令运行就好了。关键是用法，不是`apipe`这个名字。
在 2018年8月9日 +0800 10:04，alex <notifications@github.com>，写道：

你是把代码拷贝到自己的项目中运行的，还是直接运行的示例呢？
我觉得这个问题的原因是，ps 找不到名为 apipe 的进程。所以如果你这段代码运行的进程名称不叫apipe的话，就会报这个错。

如果你是把代码粘贴到你自己的项目中运行的话，尝试把cmd2 := exec.Command("grep", "apipe") 里面的"apipe"改成的你的项目编译出来的程序的名字
